spring.application.name=api-gateway
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=app_password
spring.data.redis.timeout=6000ms

spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/account/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter-replenishRate=10
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter-burstCapacity=20

spring.cloud.gateway.routes[1].id=transaction-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/transaction/**
spring.cloud.gateway.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter-replenishRate=10
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter-burstCapacity=20

spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=http://localhost:8085
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/payment/**
spring.cloud.gateway.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter-replenishRate=5
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter-burstCapacity=10
