spring.application.name=fraud-detection-service
fraud.max-transactions-per-minute=5
fraud.suspicious-amount-multiplier=5
fraud.max-balance-percentage=0.9
server.port=8083

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=fraud-detection-group
spring.kafka.consumer.auto-offset-reset=earliest

# 1. Use ErrorHandlingDeserializer to prevent the consumer loop from crashing
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# 2. Pass JacksonJsonDeserializer as the delegate to ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# 3. Ignore producer headers AND tell Jackson which class to map incoming JSON into
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.HashMap

# Producer settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

account.service.url=http://localhost:8081

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=app_password
spring.data.redis.timeout=6000ms